### PR TITLE
Feat/serializer script

### LINKED ISSUE #26: serializer script

### PR DESCRIPTION
**Pull request by tenzin3**
application developers needs pecha in md file format. 
serializer script takes base file text, add html tags(features) around the text span defined in the each annotation files(stam).

### CODE REVIEW

**Review by kaldan007 — COMMENTED** [review]
test case too big

**Comment by kaldan007** [comment]
your test is also failing

**Comment by tenzin3** [comment]
> your test is also failing

I updated and now its test is getting success.

**Comment by tenzin3** [comment]
> test case too big

ok i will add only few annotation case.

**Pull request merged**
